# Generated by Django 2.1.7 on 2020-04-16 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200416_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 16, 15, 55, 22, 696279)),
        ),
    ]
